Add security stack
Transfered from aws-root stack as part of restructuring.

diff --git a/build-change-set.cfn.yaml b/build-change-set.cfn.yaml
--- a/build-change-set.cfn.yaml
+++ b/build-change-set.cfn.yaml
@@ -100,6 +100,44 @@ Resources:
                 - CHANGE_SET_NAME=$(echo "version-bump-${BLUE_VERSION}-to-${GREEN_VERSION}-${TIMESTAMP}" | tr --squeeze-repeats [:punct:] '-')
                 - CHANGE_SET_TYPE=''
                 - TMP_DIR=$(mktemp -d)
+                ## Security Stack
+                - STACK_STATUS=$(aws --output text --query 'Stacks[0].StackStatus' cloudformation describe-stacks --stack-name ${STACK_NAME}-security || echo 'ERROR')
+                - |
+                    [ $STACK_STATUS = 'ERROR' ] && CHANGE_SET_TYPE=CREATE || [ 1 ]
+                    [ $STACK_STATUS = 'CREATE_COMPLETE' ] && CHANGE_SET_TYPE=UPDATE || [ 1 ]
+                    [ $STACK_STATUS = 'UPDATE_COMPLETE' ] && CHANGE_SET_TYPE=UPDATE || [ 1 ]
+                    [ $STACK_STATUS = 'UPDATE_ROLLBACK_COMPLETE' ] && CHANGE_SET_TYPE=UPDATE || [ 1 ]
+                    [ $STACK_STATUS = 'IMPORT_COMPLETE' ] && CHANGE_SET_TYPE=UPDATE || [ 1 ]
+                    [ $STACK_STATUS = 'IMPORT_ROLLBACK_COMPLETE' ] && CHANGE_SET_TYPE=UPDATE || [ 1 ]
+                    [ $STACK_STATUS = 'DELETE_COMPLETE' ] && CHANGE_SET_TYPE=CREATE || [ 1 ]
+                - 'echo "${CHANGE_SET_TYPE} Change Set (${CHANGE_SET_NAME}) for ${STACK_NAME}-security with stack status: ${STACK_STATUS}"'
+                - '[ ! -z $CHANGE_SET_TYPE ]'
+                - |
+                    [ -z $SKIP_CHECKSUM ] && aws s3 cp s3://${ARTIFACT_BUCKET}/cloudformation/checksums/${STACK_NAME}/security.md5sum $TMP_DIR/security.md5sum \
+                      || echo "No security.md5sum found. Probably a new CloudFormation template."
+                - |
+                    if md5sum --check --status $TMP_DIR/security.md5sum; then
+                      echo "No changes detected for security template; skipping"
+                    else
+                      aws cloudformation package \
+                        --template-file security.cfn.yaml \
+                        --s3-bucket $ARTIFACT_BUCKET \
+                        --s3-prefix cloudformation/package-templates/${STACK_NAME} \
+                        --output-template-file $TMP_DIR/security.cfn.yaml;
+                      aws s3 cp $TMP_DIR/security.cfn.yaml s3://${ARTIFACT_BUCKET}/cloudformation/package-templates/${STACK_NAME}/
+                      # TODO: use a role for the cloudformation?
+                      #--role-arn $ROLE_ARN \
+                      aws cloudformation create-change-set \
+                        --change-set-name $CHANGE_SET_NAME \
+                        --stack-name ${STACK_NAME}-security \
+                        --change-set-type $CHANGE_SET_TYPE \
+                        --capabilities CAPABILITY_IAM \
+                        --template-url "https://${ARTIFACT_BUCKET}.s3-${REGION}.amazonaws.com/cloudformation/package-templates/${STACK_NAME}/security.cfn.yaml" \
+                        --output text \
+                        --query 'Id' && \
+                        md5sum security.cfn.yaml > $TMP_DIR/security.md5sum
+                      aws s3 cp $TMP_DIR/security.md5sum s3://${ARTIFACT_BUCKET}/cloudformation/checksums/${STACK_NAME}/security.md5sum
+                    fi
                 ## DevOps Stack
                 - STACK_STATUS=$(aws --output text --query 'Stacks[0].StackStatus' cloudformation describe-stacks --stack-name ${STACK_NAME}-devops || echo 'ERROR')
                 - |
